package com.synth.couplehub.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF864B70)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD8EC)
val onPrimaryContainerLight = Color(0xFF37072A)
val secondaryLight = Color(0xFF715765)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFBD9EA)
val onSecondaryContainerLight = Color(0xFF291521)
val tertiaryLight = Color(0xFF8C4A60)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E2)
val onTertiaryContainerLight = Color(0xFF3A071D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F9)
val onBackgroundLight = Color(0xFF211A1D)
val surfaceLight = Color(0xFFFFF8F8)
val onSurfaceLight = Color(0xFF21191D)
val surfaceVariantLight = Color(0xFFF0DEE4)
val onSurfaceVariantLight = Color(0xFF504349)
val outlineLight = Color(0xFF827379)
val outlineVariantLight = Color(0xFFD3C2C9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372E31)
val inverseOnSurfaceLight = Color(0xFFFCEDF1)
val inversePrimaryLight = Color(0xFFF9B1DB)
val surfaceDimLight = Color(0xFFE5D6DB)
val surfaceBrightLight = Color(0xFFFFF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F4)
val surfaceContainerLight = Color(0xFFF9EAEE)
val surfaceContainerHighLight = Color(0xFFF3E4E9)
val surfaceContainerHighestLight = Color(0xFFEEDFE3)


val primaryDark = Color(0xFFF9B1DB)
val onPrimaryDark = Color(0xFF501E40)
val primaryContainerDark = Color(0xFF6A3457)
val onPrimaryContainerDark = Color(0xFFFFD8EC)
val secondaryDark = Color(0xFFDEBECE)
val onSecondaryDark = Color(0xFF3F2A36)
val secondaryContainerDark = Color(0xFF57404D)
val onSecondaryContainerDark = Color(0xFFFBD9EA)
val tertiaryDark = Color(0xFFFFB1C8)
val onTertiaryDark = Color(0xFF541D32)
val tertiaryContainerDark = Color(0xFF703348)
val onTertiaryContainerDark = Color(0xFFFFD9E2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF181115)
val onBackgroundDark = Color(0xFFEDDFE4)
val surfaceDark = Color(0xFF181114)
val onSurfaceDark = Color(0xFFEEDFE3)
val surfaceVariantDark = Color(0xFF504349)
val onSurfaceVariantDark = Color(0xFFD3C2C9)
val outlineDark = Color(0xFF9C8D93)
val outlineVariantDark = Color(0xFF504349)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEEDFE3)
val inverseOnSurfaceDark = Color(0xFF372E31)
val inversePrimaryDark = Color(0xFF864B70)
val surfaceDimDark = Color(0xFF181114)
val surfaceBrightDark = Color(0xFF40373A)
val surfaceContainerLowestDark = Color(0xFF130C0F)
val surfaceContainerLowDark = Color(0xFF21191D)
val surfaceContainerDark = Color(0xFF251D21)
val surfaceContainerHighDark = Color(0xFF30282B)
val surfaceContainerHighestDark = Color(0xFF3B3236)

val pinkGradient = listOf<Color>(
    Color(0xFFF896C7) ,
    Color(0xFFFFDDEE) ,
    Color(0xFFFFE9F3) ,
    Color(0xFFFFFFFF)
)






